import axios from 'axios';
const API_URL = process.env.REACT_APP_API_URL || 'http://localhost:5000/api';
const api = axios.create({ baseURL: API_URL, timeout: 10000 });
api.interceptors.request.use(c => { const t = localStorage.getItem('rg_token'); if (t) c.headers.Authorization = `Bearer ${t}`; return c; });
api.interceptors.response.use(r => r, e => { if (e.response?.status === 401) { localStorage.removeItem('rg_token'); localStorage.removeItem('rg_user'); window.location.href = '/'; } return Promise.reject(e); });
export const managerRegister = d => api.post('/auth/manager/register', d);
export const managerLogin    = d => api.post('/auth/manager/login', d);
export const driverLogin     = d => api.post('/auth/driver/login', d);
export const logout          = () => api.post('/auth/logout');
export const getDrivers      = () => api.get('/drivers');
export const createDriver    = d => api.post('/drivers', d);
export const updateDriver    = (id,d) => api.put(`/drivers/${id}`, d);
export const deleteDriver    = id => api.delete(`/drivers/${id}`);
export const reportIssue     = d => api.post('/issues', d);
export const getIssues       = () => api.get('/issues');
export const verifyIssue     = id => api.post(`/issues/${id}/verify`);
export const falseReport     = id => api.post(`/issues/${id}/false-report`);
export const getMyAlerts     = () => api.get('/issues/alerts/my');
export const markAlertSeen   = id => api.put(`/issues/alerts/${id}/seen`);
export const setRoute        = d => api.post('/routes/set', d);
export const updateLocation  = d => api.put('/routes/location', d);
export const completeRoute   = () => api.post('/routes/complete');
export const getMyRoutes     = () => api.get('/routes/my');
export const getCurrentRoute = () => api.get('/routes/current');
export const getAllRoutes     = () => api.get('/routes/all');
export const getDashboardStats = () => api.get('/dashboard/stats');
export const getMyStats      = () => api.get('/dashboard/me');
export default api;
